name: Maven_Build_Package 

on:
  push:
    branches:
      - 'main'

jobs:
  build_package:
    runs-on: ubuntu-latest
    steps:
    - name: Maven Version
      run: mvn -version

    - name: Checkout Repo
      uses: actions/checkout@v3
      with:
        ref: main  

    - name:  Check Maven Project Working Directory
      run: |
        pwd
        ls -lrth
        echo "workspace : ${{ github.workspace }}"

    - name:  Validate POM file
      run: |
        mvn validate

    - name:  Compile the code
      run: |
        mvn compile    

    - name:  Test the code
      run: |
        mvn test

    - name:  Clean the code
      run: |
          mvn clean 

    - name:  Create a deployable package
      run: |
        mvn package                   

        


